### ISSUE TITLE
New Features and TODOs

### ISSUE THREAD

**Issue by OrkoHunter** [pep8speaks-org/pep8speaks#1]
- [x] Do not comment when no suggestions are there on PR being opened.
 - [x] Do not comment repetitively.
 - [x] Add comment when no issues.
 - [x] Use keywords `quiet` and `resume` in mentions to shut off @pep8speaks for the Pull Request and then resume when it's required.
 - [x] List repositories using the bot
 - [x] Allow option to lint only the diff
 - [x] Do Not comment while `updating` the PR if there was no errors while `submitting`
 - [x] Add to README about fixing the errors (pycodestyle)
 - [x] Convert filename to link the file
 - [x] Link line numbers
 - [x] Turn the error codes into web links for queries
 - [x] Show instructions on index.html.
- [x] Comment `@pep8speaks suggest diff` as review comment summary to get the diff with suggested changes
 - [x] Comment `@pep8speaks pep8ify` to create a PR against the existing PR for fixes
 - [x] Change licence and allow the service for commercial use
 - [x] Add secret key for payloads
 - [x] Use request headers to classify actions
 - [x] Do not comment on pr created by pep8speaks
 - [x] Add pycodestyle config usage
 - [x] Do Not comment if there are no Python files changed.
 - [x] Use the .pep8speaks.yml file from the branch of the PR.
 - [x] Set the bot to follow all the users
 - [x] Use integration installation webhook
 - [x] Work on status code
 - [x] Configure `autopep8` to respect `.pep8speaks.yml`
 - [x] Truncate comment if the file path is too long

**Comment by sethmlarson** [comment]
How about changing the 'In the file `/blah/blah/blah`' message to have the file name be a link to the file in question? Would make navigating from the PR have a much better flow. :)

**Comment by OrkoHunter** [comment]
@SethMichaelLarson That would be a useful change! :) Would you like to work on it?

**Comment by OrkoHunter** [comment]
@SethMichaelLarson That has now been implemented. :)
> How about changing the 'In the file /blah/blah/blah' message to have the file name be a link to the file in question? Would make navigating from the PR have a much better flow. :)

**Comment by sethmlarson** [comment]
@OrkoHunter This is great to hear! Thank you! :tada:

**Comment by jaywink** [comment]
Thanks for this! Any chance of being able to configure the bot to not comment at all if it doesn't find anything? I would like to get rid of the "Thanks for your PR, no issues in any files" etc comment - or am I missing an existing configuration value?

**Comment by OrkoHunter** [comment]
@jaywink Thanks for trying it out. I have added a [new commit](https://github.com/OrkoHunter/pep8speaks/commit/717a28bbd48264fe4bd3fc108ea3d8f0f289102b) enabling a new config option no_blank_comment which when set to True, stops the bot from making no-error comments.

Simply add
```
no_blank_comment: True
```
in the `.pep8speaks.yml` file.

Cheers !

**Comment by jaywink** [comment]
@OrkoHunter awesome, thanks a lot for the quick addition - appreciate it! :)

**Comment by OrkoHunter** [comment]
Need help regarding access to private repositories : http://stackoverflow.com/q/42316916/4698026

**Comment by OrkoHunter** [comment]
GitHub support replied. [We are all set for Private repositories](https://github.com/OrkoHunter/pep8speaks/wiki/Instructions-to-deploy-a-fork) now!

@daneah Hope you could make use of it now :D
