### ISSUE TITLE
pep8speaks reports both W503 and W504

### ISSUE THREAD

**Issue by kohr-h** [pep8speaks-org/pep8speaks#103]
Apparently there has been a recent change in `pycodestyle` that favors line breaks before binary operators over breaks after them:

```python
# Old style
x = (123545925240502 +
     74979743 *
     8383)
# New style
x = (123545925240502
     + 74979743
     * 8383)
```
Currently, pep8speaks complains about both variants: the first one triggers W504, the second one W503.

In principle, W504 should be ignored by default in pycodestyle, but that doesn't seem to be the case.

Should one of the two go into the list of default ignores?

**Comment by OrkoHunter** [comment]
Hi @kohr-h!

Can you let me know about the version of pycodestyle with this change? As soon as it gets published on pypi, I can deploy the latest version.

pep8speaks does not have any default pycodestyle configuration. I recommend using .pep8speaks.yml to configure pycodestyle according to your needs.

**Comment by kohr-h** [comment]
@OrkoHunter I'm not entirely sure. The [changelog](https://pycodestyle.readthedocs.io/en/latest/developer.html#id3) mentions W504 as a new check in version 2.4.0 (released 2018-04-10), but at the same time writes "This check is ignored by default." Still, pep8speaks started emitting W504 a while ago (end of 2018 maybe?), and it's hard to avoid both warnings at the same time :-)

With default configuration, I meant the config of pep8speaks itself, which I guess people take as template?

**Comment by OrkoHunter** [comment]
Oh! Sure, it makes sense to me.

I will add W504 in the README.
