### ISSUE TITLE
Does pep8speaks ignores config?

### ISSUE THREAD

**Issue by TomaszKolek** [pep8speaks-org/pep8speaks#105]
Hey folks!

I have some problems with configuring pep8speaks. It seems pep8speaks ignores config file. Could you please check it?
The config file is on dev branch here:
https://github.com/CiviWiki/OpenCiviWiki/blob/dev/.pep8speaks.yml

And we have PR https://github.com/CiviWiki/OpenCiviWiki/pull/335 that has pep8speaks comment with E501 with max line 79 even though on config file we have 120 chars as the limit.

**Comment by TomaszKolek** [comment]
Sorry Bot just probably needed more time!

Sorry for creating this issue.

**Comment by OrkoHunter** [comment]
Oh hey @TomaszKolek !

Glad it worked out. :)
