### ISSUE TITLE
Logo/Avatar needs update | Need ideas

### ISSUE THREAD

**Issue by OrkoHunter** [pep8speaks-org/pep8speaks#110]
Current logo - 
![24736507](https://user-images.githubusercontent.com/8065913/54104543-4cbd4900-43f6-11e9-9825-afec9e3b7aec.png)

This was a 30 minutes effort with very little design skills almost two years ago. I like it but would love to design something new which is elegant and creative.

Ideas/Contributions are welcome!

**Comment by aadibajpai** [comment]
Do you have a specific design in mind?

**Comment by OrkoHunter** [comment]
Hi @aadibajpai !

I do not have anything specific in mind! I have never designed a logo before and I am curious about resources/ideas/tips for doing so. I am willing to learn what makes a logo elegant and creative.

**Comment by aadibajpai** [comment]
![pep8speaks_check](https://user-images.githubusercontent.com/27063113/54634684-b7325100-4aa8-11e9-9a80-6f907472462b.png)
![pep8speaks](https://user-images.githubusercontent.com/27063113/54634686-b7cae780-4aa8-11e9-8503-9af2eb2a992e.png)


What do you think?

**Comment by OrkoHunter** [comment]
Hi @aadibajpai !

Wow! Thank you so much for adding this. This looks neat!

**Comment by aadibajpai** [comment]
@OrkoHunter let me know if you want to use it and I'll add a finish and send it to you. Otherwise I'll just use it for whatever lol. PEP8Speaks is definitely useful for me so I wanted to give back to the project 😄

**Comment by thealphadollar** [comment]
@OrkoHunter Please update.
