### ISSUE TITLE
Why not comment in commit status?

### ISSUE THREAD

**Issue by MrKiven** [pep8speaks-org/pep8speaks#13]
https://developer.github.com/v3/repos/statuses/

**Comment by OrkoHunter** [comment]
Hi @MrKiven,
Thank you for this. I agree for anything to make the bot less and less noisy! I have a question though, does the commit status enforce green/red tick on the PR or it's just a comment? I'm sorry I did not look it through.

**Comment by daneah** [comment]
I was about to open an issue with this very suggestion! @OrkoHunter: The commit status would create a green/red tick on the PR, and the nice thing about that is that repository owners can choose to enforce this status check on all pull requests (unenforced by default).

The absolute cleanest way to do this would be to store the linting results on an external URL that can then be supplied in the status via `target_url`. Then you could do away with the PR comments completely. This obviously necessitates a great deal more work, so opting for the combined comment + status approach for now seems reasonable and is at least a step in that direction.

**Comment by OrkoHunter** [comment]
@daneah @MrKiven I tried to hack on the commit status feature. The only limitation to it is that there should be push access to the bot for making the status comment.

**Comment by daneah** [comment]
@OrkoHunter oh, that could potentially be a blocker for some...didn't realize that was necessary.

**Comment by OrkoHunter** [comment]
I think #17 solves this issue partially :)

**Comment by daneah** [comment]
@OrkoHunter that's great! I think the main impetus for commit statuses is that they can be enforced natively in GitHub to disallow merging if a status is failing, etc. #17 reduces the noise, however, which is great.
