### ISSUE TITLE
Slowness on large codebase?

### ISSUE THREAD

**Issue by daneah** [pep8speaks-org/pep8speaks#14]
I installed pep8speaks on a personal repository of mine and it worked very well 🎉 

When installed on one of our largest repositories, however, pep8speaks seemed never to finish running `pycodestyle` and thus never provided any feedback.

I first posited that this might be because `pycodestyle` was running over the full codebase and only reporting on the changed files, but my reading of the code says that it is in fact running only on the changed files. Do you have other inklings about what might be causing the slowness or total lack of feedback from pep8speaks?

**Comment by OrkoHunter** [comment]
@daneah I think the "large repository" you are talking about is not public and hence @pep8speaks has no way to access it. I was thinking of making the service possible for private repositories too but then there were a lot of things to deal with and my semester break got over.

I'd still love to have a workaround listed on the repository and a "deploy to Heroku" button for people interested in running the service for their private repos being their own maintainers.

**Comment by daneah** [comment]
Thanks for the clarity—I didn't realize this integration would not work on private repositories! I assumed receiving the permissions would be enough for it to handle public or private equally. What are the the additional pieces needed for that to work?

We were considering forking this and running it ourselves anyway for better privacy guarantee, so maybe we can look further into that soon 😄 

Thanks again!

**Comment by OrkoHunter** [comment]
The integration simply works on payloads and no special permissions are granted while installing it. For it to work for private repositories, an OAuth app needs to be created.

An alternative is to use the access token of a user(@pep8speaks in this case) which has the permissions to the repo/orgs.

**Comment by OrkoHunter** [comment]
I'm closing this now. You're welcome. :)
