### ISSUE TITLE
No comment posted after updating PR with a commit

### ISSUE THREAD

**Issue by desilinguist** [pep8speaks-org/pep8speaks#143]
I installed pep8speaks and added the `.pep8speaks.yml` file to two of my repositories. However, while one of them is fine, the second repo is not seeing any comments at all. For example, in [this PR](https://github.com/EducationalTestingService/skll/pull/479), I updated the PR by merging `master` (that contained the `.pep8speaks.yml` file) into it but am not seeing any comments at all. 

Not sure if I am doing something wrong?

**Comment by desilinguist** [comment]
What's interesting is that if I comment `pep8speaks suggest diff` in that same PR, that works for some reason.

**Comment by desilinguist** [comment]
It works fine now.

**Comment by dizcza** [comment]
How did you solve it?
