### ISSUE TITLE
Skip unbreakable lines linke sphinx tables (rst)

### ISSUE THREAD

**Issue by uvchik** [pep8speaks-org/pep8speaks#157]
Is it possible to skip unbreakable lines?

As I know, it is not possible to break rows in a sphinx table (rst) but it is kind of confusing to split these messages from reasonable messages.

https://github.com/oemof/oemof/blob/4462e2f63c40ca0bc3357004473a968681439d15/oemof/solph/components.py#L1258

**Comment by OrkoHunter** [comment]
Hi @uvchik, PEP8Speaks uses either `pycodestyle` or `flake8` as its linters. See [configuration](https://github.com/OrkoHunter/pep8speaks#configuration). So, any specific configuration about linting belongs to them, and can be passed on by `.pep8speaks.yml`.

I believe the standard way to ignore specific lines is by using `#noqa` flags. See [Ignoring Errors with Flake8](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html). Please set the PEP8Speaks linter to `flake8` use this.

You can also ignore `E501` which is the PEP8 error for long lines. But I think this is not wise. :)
