### ISSUE TITLE
Pep8speaks is not triggered

### ISSUE THREAD

**Issue by dizcza** [pep8speaks-org/pep8speaks#158]
I tried reinstalling pep8speak service in NeuralEnsemble/elephant a few times with no luck.
Github shows pep8speak service is on but it does not check the pull requests.
For example, in this PR https://github.com/NeuralEnsemble/elephant/pull/303 there is no comment from pep8speaks.
It has been already for half a year or so. I thought it's a known issue, but it's not - I've just setup pep8speak for https://github.com/INM-6/viziphant-new and it works fine!
So there is some issue with pep8speaks and NeuralEnsemble. Please check. The permissions are given.

**Comment by OrkoHunter** [comment]
Hi @dizcza, thanks for reporting the issue. I can confirm that the payloads are being delivered to the app, hence there is no problem with the installation.

**Comment by OrkoHunter** [comment]
Hello @dizcza, PEP8Speaks is working on the repository https://github.com/NeuralEnsemble/elephant/pull/304

I believe for https://github.com/NeuralEnsemble/elephant/pull/303, there is no PEP8 errors and by default the bot is set to not comment. You can configure the behavior by [`.pep8speaks.yml`](https://github.com/OrkoHunter/pep8speaks#configuration)

**Comment by dizcza** [comment]
Ah, I see, sorry.
Thank you for checking it.

**Comment by OrkoHunter** [comment]
You're welcome. :)
