### ISSUE TITLE
Continiously updating the last comment

### ISSUE THREAD

**Issue by glemaitre** [pep8speaks-org/pep8speaks#16]
Right now, the bot is posting a new comment when the PEP8 status is changing.
It could be nice to have an even more silent mode, but always updating the initial comment.
It reduces the amount of noise in emails in large PR with a cleaner thread as well.
This is something that codecov is doing.

**Comment by OrkoHunter** [comment]
This sounds perfect to me. Thank you for the suggestion ! I'll get to the implementation as soon as possible.

**Comment by OrkoHunter** [comment]
A live example https://github.com/OrkoHunter/test-pep8speaks/pull/38
