### ISSUE TITLE
"Indentation is not a multiple of four" potential error?

### ISSUE THREAD

**Issue by max-sixty** [pep8speaks-org/pep8speaks#161]
Any ideas what's going on here? It seems to be a mistake; though not impossible there's some invisible character issue our end. Flake8 and black checks pass, though.

https://github.com/pydata/xarray/pull/3643#issuecomment-608090328

**Comment by OrkoHunter** [comment]
Thanks for reporting! The bot's comment is wild.

**Comment by OrkoHunter** [comment]
Hi @max-sixty, I triggered the bot for this PR and looks like it has updated the comment. Something might have gone wrong with the request when that useless comment was made. And the there was no additional commit, so the bot didn't get a chance to update the comment.

Anyhow, it's fixed. But thanks a lot for reporting! 🙇

**Comment by max-sixty** [comment]
Thanks @OrkoHunter
