### ISSUE TITLE
Broken dependency flask-session

### ISSUE THREAD

**Issue by changning-niu** [pep8speaks-org/pep8speaks#164]
Deployment on Heroku failed because of this issue of flask-session:
https://github.com/fengsp/flask-session/pull/114

**Comment by OrkoHunter** [comment]
That's true! Thanks for reporting @changning-niu 

The current CI build is failing as well.
https://travis-ci.org/github/OrkoHunter/pep8speaks/builds/670887717?utm_source=github_status&utm_medium=notification

My comment on this issue https://github.com/pytest-dev/pytest-flask/issues/119

**Comment by OrkoHunter** [comment]
Sad that [flask-session](https://github.com/fengsp/flask-session/pull/114) is broken for so long. :(
