### ISSUE TITLE
How to stop pep8speaks from checking certain directories like for example alembic

### ISSUE THREAD

**Issue by Haider8** [pep8speaks-org/pep8speaks#170]

**Comment by OrkoHunter** [comment]
Hi ! This can be done by having [.pep8speaks.yml](https://github.com/OrkoHunter/pep8speaks#configuration) in the root of the repository.

If you have set your linter to `pycodestyle`, use the `pycodestyle.exclude` section in the config file to set the directories/files you want to exclude. You can find more details on the [pycodestyle documentation](https://pycodestyle.pycqa.org/en/latest/intro.html#configuration).

The same can be done for flake8. See [an example](https://github.com/python-gsoc/python-blogs/blob/feee47dc3cf01d902804ee782d808e00d46ca4cc/.pep8speaks.yml). Hope this helps. :)
