### ISSUE TITLE
Please use non-breaking space in "PEP 8"

### ISSUE THREAD

**Issue by MikhailRyazanov** [pep8speaks-org/pep8speaks#172]
I suggest to use a non-breaking space (U+00A0) in "PEP 8" in comments, since currently (with the regular space) they sometimes look like

> ... We checked the lines you've touched for PEP
> 8 issues, and found:

which is confusing ("8 issues", OMG!).

**Comment by MikhailRyazanov** [comment]
Here is an example (underlined in red):
![8issues](https://user-images.githubusercontent.com/12854133/83091362-40072e00-a058-11ea-815c-d46498603547.png)

**Comment by OrkoHunter** [comment]
Fixed in #177
