### ISSUE TITLE
Suggestion for escaped parenthesis

### ISSUE THREAD

**Issue by Lewiscowles1986** [pep8speaks-org/pep8speaks#181]
Hi, Cool tool

I just unexpectedly got a visit from the pep8speaks fairy when PR'ing pandas.

I was changing some code that had no brackets and was matching an exception using a `pytest.raises` context block.

It's not a feature I use, as I think scanning exceptions for details can be problematic, but I wanted to keep test logic as it was in a style of that project.

In any case I did not realize the intention of the code was to pattern match, so when running it would fail, and the only way to have it pass is to remove the parenthesis, or escape them.

I added `r` modifier to the string and flake8 and this tool accepted the correction, so I was wondering if it might be worth a PR to add a suggestion / note to the error message to say something along the lines of.

> We've noticed you're escaping parenthesis. This should only be necessary for regex string patterns. If this is the case, add the `r` modifier to the start of your string and escape parenthesis.

This tool and flake, and black did not complain about `rf` modifiers, but I've no idea if it should be `fr` in such a case that it matters to anyone, perhaps a code snippet underneath (can be non-digetic) might help people further understand.

**Comment by OrkoHunter** [comment]
Hi Lewis!

Thank you for creating the issue. The idea of suggesting changes based on the errors are worth exploring.

The suggestion seems like something a linter should do. PEP 8 Speaks is merely a wrapper over the linters `pycodestyle` and `flake8`. If these linters start giving suggestions like you wrote above, then PEP 8 Speaks should comment the same too.

I am not aware if these linters print out any suggestions like these currently. Let me know if you are aware. :)

**Comment by Lewiscowles1986** [comment]
I should have read the code to make sure the problem was here. I may look at the tools.
