### ISSUE TITLE
Has PEP8 Speaks stopped working or am I doing something wrong?

### ISSUE THREAD

**Issue by ikerexxe** [pep8speaks-org/pep8speaks#189]
I'm testing this app to know if I can integrate it in a big project, but so far PEP8 Speaks doesn't provide any feedback in my PRs. These are the steps that I'm following.

I installed the app for my repository (flake8-action-test).
![Screenshot from 2022-10-04 12-01-40](https://user-images.githubusercontent.com/2324748/193792257-0ee4bc44-5bbd-4c34-8db5-8b4ea809176f.png)

Moreover, I configured the application with the [.pep8speaks.yml](https://github.com/ikerexxe/flake8-action-test/blob/main/.pep8speaks.yml) file.

Finally, I created two PRs: [one with the code formatted correctly](https://github.com/ikerexxe/flake8-action-test/pull/1) and [the other with incorrect formatting](https://github.com/ikerexxe/flake8-action-test/pull/2). Taking into account that I set `no_blank_comment` to false I was expecting to get feedback in both PRs, but I'm getting nothing.

So, I'm wondering if PEP8 Speaks has stopped working or if I'm doing something wrong.

PS: I'd like to mention that the [Github search for commenter:pep8speaks](https://github.com/search?o=desc&q=commenter%3Apep8speaks&s=created&type=Issues) doesn't show any message in the last 20 days.

**Comment by OrkoHunter** [comment]
Hi @ikerexxe ! It has indeed stopped working. It was hosted on Heroku, but then [Heroku decided not to accept Indian cards](https://devcenter.heroku.com/changelog-items/2305) and so my account has been closed now.

I'm looking for an alternative deployment solution, maybe proper AWS. Please allow me some time to do it. :)

**Comment by ikerexxe** [comment]
Thanks for reaching out so fast. Please take your time to find a good alternative.

**Comment by xylar** [comment]
@OrkoHunter, is there any update?  It feels like it's time for my projects to move to an alternative checker but I've really enjoyed pep8 speaks and would be sad to move on.

**Comment by OrkoHunter** [comment]
@xylar Thanks for the reminder! In my last attempt, I looked at some of the alternative hosting solutions. The requirements I had in mind were -

1. Should be easy to deploy changes as new releases are made. Ideally no CLI/Keys involved and deployment is triggered via webhook.
2. Should be cheap - ideally less than 10$ per month.

I discovered [Fly.io](https://fly.io/) as a good alternative. I spent some time learning and trying it out for another personal project. Let me block some time this weekend and try deploying pep8speaks there too. 🙂

**Comment by marcorosa** [comment]
Hi @OrkoHunter is there any update on this issue?

**Comment by OrkoHunter** [comment]
I'm sorry to keep everyone waiting here. After several failed attempts to revive the backend, I'm opening this up for help and anyone who would like to take ownership. I don't want to be a blocker on this project. I've posted more details at https://github.com/pep8speaks-org/pep8speaks/issues/191 about looking for a new maintainer and a sponsor.

Really sorry that I have not been helpful lately to the project. 🙏

**Comment by jethror1** [comment]
Has this now been fixed? We noticed it started running again the other day on new PRs, if this was you then thank you! :tada:

**Comment by OrkoHunter** [comment]
Hey @jethror1, Yes! The project has a new maintainer @tushar5526 who revived the project. So all credits to him and his team! 👏

**Comment by tushar5526** [comment]
Closing this now. @jethror1 do let us know if you have any feedback!
