### ISSUE TITLE
🚨 Looking for a maintainer and sponsor to restart this project

### ISSUE THREAD

**Issue by OrkoHunter** [pep8speaks-org/pep8speaks#191]
## Context

PEP8Speaks has always been a hosted solution allowing everyone to lint their Pull Requests on GitHub. Since [Heroku practically got killed](https://www.reddit.com/r/webdev/comments/wxi78n/heroku_free_plans_will_be_removed/) and [never implemented the support for Indian cards](https://devcenter.heroku.com/changelog-items/2305), PEP8Speaks has been down for about a year now.

I am no longer capable of maintaining this project in terms of code as well as infrastructure that this requires. I tried exploring deployments on Fly.io and other platforms on weekends, only to fail after hours of attempts.

## Need

In order to revive this project, it **needs a new maintainer** - someone who can deploy the backend which can support all the events from its GitHub app. It also requires an infrastructure which could be free but can also take 5-10$ per month depending upon the solution used.

If you'd like to take ownership, I'm happy to jump on a call with you and explain the technical details. Please reach out on himanshu [at] orkohunter.net.

I've already converted this project into an org, so happy to add you as an admin on the project.

## Alternatives

The code is open source and anyone can deploy this and spin up their own hosted PEP8Speaks for their projects. Should we keep this model? It is disadvantageous to open source projects which have been using this to reduce PR review time.

**Comment by tushar5526** [comment]
Hey, thank you for putting this project together. I and @Mr-Sunglasses would love to maintain the project and have some cloud credits with us that will help run this for a few more years :D. Sharing you more details over the email.

**Comment by OrkoHunter** [comment]
Thank you @tushar5526 and @Mr-Sunglasses for stepping up as maintainers and reviving the project. ❤️
