### ISSUE TITLE
Update tests and move to GHAs

### ISSUE THREAD

**Issue by tushar5526** [pep8speaks-org/pep8speaks#194]
- Tests need to be refactored 
- Move to GHAs to enable CI

**Comment by Mr-Sunglasses** [comment]
I'm taking up on this issue 🤙🏻

**Comment by kyluca** [comment]
Hi,

Just checking if this issue is still relevant to the project in its current state?

If it's not actively being worked on I'd be happy to submit a PR for Hacktoberfest?

Cheers,
Kyle

**Comment by OrkoHunter** [comment]
Please do!

**Comment by kyluca** [comment]
PR up here to enable the tests on GHA: https://github.com/pep8speaks-org/pep8speaks/pull/234

Let me know what you think :)

**Comment by Mr-Sunglasses** [comment]
Thanks a lot @kyluca for the PR, I'll review it :-)
