### ISSUE TITLE
[Docs] Document the deployment process 

### ISSUE THREAD

**Issue by tushar5526** [pep8speaks-org/pep8speaks#197]
We might switch cloud providers or have a new sponsor in future. Documenting the process will help in re-deploying.

**Comment by SD-13** [comment]
@tushar5526 Can I work on this issue? Thanks!

**Comment by tushar5526** [comment]
Hey @SD-13, we are planning to take this up, as there is some context that needs to be there before you can write this doc. I would really love if you can help out with other issues 😄

**Comment by SD-13** [comment]
@tushar5526 Sure, I will look for other issues. Thanks!
