### ISSUE TITLE
What is the Python version used in the codebase ?

### ISSUE THREAD

**Issue by ashwch** [pep8speaks-org/pep8speaks#20]
Apart from runtime.txt(Python 3.6.0) it is not mentioned anywhere which Python versions are we supposed to support. Can we make that clear somewhere?

**Comment by OrkoHunter** [comment]
I'm not quite sure here. How does the Python version affect the pycodestyle's results (or PEP8 basically)?

**Comment by ashwch** [comment]
Let's say we add any Python 3.6+ specific syntax to the codebase and someone wants to deploy the app to a platform(other than Heroku) that doesn't support 3.6 yet, then they won't be able to use it.

**Comment by OrkoHunter** [comment]
Oh, That's a good point ! I am not entirely sure but the codebase is Python 2.7 & Python 3 compatible as of now. But I won't push for the backwards compatibility anymore and stick to just using Python 3.

**Comment by jfboismenu** [comment]
Hey @OrkoHunter , I think that it is unfortunate that you considering dropping 2.7 support. The entire movie/tv VFX industry is based around 2.7 for the foreseable future, until 2019 at the very least.

**Comment by OrkoHunter** [comment]
Hey @jfboismenu, to make the issue more clear, PEP8Speaks integration supports __all__ versions of Python.
The issue is about the codebase of the integration itself, which supports 2.7 and 3.4+ as of now.
