### ISSUE TITLE
Investigate adding very simple monitoring to make sure pep8speaks server is up and running. 

### ISSUE THREAD

**Issue by tushar5526** [pep8speaks-org/pep8speaks#213]
The problem statement is to ensure the pep8speaks server has not stopped working and notify via email if the backend is not working.

**Comment by tushar5526** [comment]
@Mr-Sunglasses would it be possible to get a public uptime page from `uptime-kuma` ?

**Comment by Mr-Sunglasses** [comment]
@tushar5526 Working on this.

**Comment by Mr-Sunglasses** [comment]
@tushar5526 [status page](https://kuma.fosscu.org/status/pep8speaks ) link, should I add to README.md
