### ISSUE TITLE
Comments link to non-existing repository

### ISSUE THREAD

**Issue by jasiekmarc** [pep8speaks-org/pep8speaks#29]
We have a team (private) repository owned by the team's leader, and a bunch of Github users having access to it and proposing Pull Requests. In the comment, @pep8speaks links to the changed files and lines having errors. Unfortunately, the link (generated here: https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L217) points to the PR authors' non-existing repositories rather than the team's repository.

**Comment by OrkoHunter** [comment]
@jasiekmarc I believe the bot runs on the branch of the author of the PR. So, if the branch is on the fork of the user, it would like over there. I did not get the part when you say that the author's repository does not exist. How does he create a Pull Request then? Is it created from the same repository with a different branch?

**Comment by jasiekmarc** [comment]
Exactly. We just create branches in the original repository, and them merge them to master.

**Comment by OrkoHunter** [comment]
Okay thanks. I'll take a look in the github payload and modify which url to use. If you have the fix, it'd be great if you could submit a PR.

**Comment by OrkoHunter** [comment]
Closing this issue. Please re-open if the error still persists.
