### ISSUE TITLE
Problem with .pep8speaks.yml and private repositories

### ISSUE THREAD

**Issue by chinskiy** [pep8speaks-org/pep8speaks#33]
Greetings again(3-rd time for today)
I have problem with .pep8speaks.yml and private repositories - seems like app don't see this file - any suggestions? in heroku logs nothing.
ps. With public works good.

**Comment by OrkoHunter** [comment]
1. Make sure the indentations are properly working. Please send it to me, and I might verify.
2. Are you using the `BOT_USERNAME` and `BOT_PASSWORD` os vars? Tokens don't seem to work here.
3. `.pep8speaks.yml` file is taken from the branch of the PR (and not the repository). So, make sure your PR is rebased/updated with the file.

I can only help with these suggestions as of now.

**Comment by chinskiy** [comment]
@OrkoHunter thanks for suggestions
1. I use [this](https://github.com/OrkoHunter/pep8speaks#configuration) configuration example.
2. Yes, recheck them.
3. I consider it.
but I think problem is [here](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L120) because we use organisation and url to `.pep8speaks.yml` is `https://raw.githubusercontent.com/{organisation}/{repository}/{sha}/{file}` **without** user

also I can make curl request to get raw file only with 'Authorization: token {token}' in header. Are you sure that you need to make request with **BOT_USERNAME** and **BOT_PASSWORD**?

**Comment by OrkoHunter** [comment]
> but I think problem is here because we use organisation and url to 

Doesn't [this](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L123) add the user credentials as `auth` ?

**Comment by chinskiy** [comment]
@OrkoHunter problem is not in user credentials - problem in url.
[Here](https://github.com/chinskiy/pep8speaks/commit/58ecbd6bb2dd1a3c859f528667e9463fac690824) my fix what works with my public and private repo.

I think here can be used repo.full_name from github webhook([url](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/handlers.py#L92)). What you think?

> Doesn't this add the user credentials as auth ?

I mean what the reason to use [auth](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L117) if you add [auth token](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L116)
this not related to this issue

**Comment by OrkoHunter** [comment]
> I mean what the reason to use auth if you add auth token

I think this happened because the user token I had generated initially (for working with public repositories) was with minimal permissions and hence I had to add the `auth` for working with private repositories. Of Course it can work with one only.

**Comment by chinskiy** [comment]
PR #37 merged.
Close issue.
