### ISSUE TITLE
Implement `@pep8speaks pep8ify` as a comment instead of review comment

### ISSUE THREAD

**Issue by OrkoHunter** [pep8speaks-org/pep8speaks#36]
Earlier, comments on a PR used to fall in the category of GitHub Issues API for which PEP8Speaks integration was not configured (I had set it up only for Pull Request API). GitHub did not me allow to change payload permissions. Thanks to GitHub for acting on it and adding the option to update the permissions now and receive payloads for the comments.

`@pep8speaks pep8ify` and other mentions should now be triggered from the issue comment itself (Currently it works as a PR review comment)

Dear @cadair @stefanv @rasbt @soupault and others, You must have received an email asking for this change. It would be great if you would allow the integration to receive triggers for the comments. I would implement the feature as soon as possible.

Thanks a ton!

**Comment by stefanv** [comment]
I only received the following email, which contains a broken link:

```
You can accept or decline this update. View all of PEP8 Speaks's permissions on GitHub.

<a href="https://github.com/settings/installations/16777/permissions/update">View update</a>
```

**Comment by stefanv** [comment]
OK, they had the link slightly wrong, but I found it and fixed it: 
https://github.com/organizations/scikit-image/settings/installations/16777
