### ISSUE TITLE
Add to .yml file message configuration when there are no PEP8 issues   

### ISSUE THREAD

**Issue by chinskiy** [pep8speaks-org/pep8speaks#38]
I wanna to make possibility to change [this](https://github.com/OrkoHunter/pep8speaks/blob/master/pep8speaks/helpers.py#L278) message.
@OrkoHunter What you thin about that?

**Comment by OrkoHunter** [comment]
Works for me. +1

**Comment by OrkoHunter** [comment]
Closed in #39
