### ISSUE TITLE
Сover code with tests

### ISSUE THREAD

**Issue by chinskiy** [pep8speaks-org/pep8speaks#40]
Hi @OrkoHunter 
I think it's reasonable to write some unit test and add them to CI because now it's like minefield.

**Comment by OrkoHunter** [comment]
True! I verify every patch with manually creating a test PR on [OrkoHunter/test-pep8speaks](https://github.com/orkohunter/test-pep8speaks) and sending the payload (copying it from the github developer settings) on the local server through a jupyter notebook to verify if everything worked properly. 

This sure is a minefield. :D

**Comment by OrkoHunter** [comment]
Some of the core features are now being tested on CI! #100
