### ISSUE TITLE
[Fixed] Display pep8 issues with line numbers in descending order

### ISSUE THREAD

**Issue by Punyaslok** [pep8speaks-org/pep8speaks#51]
It would be helpful if there is an option to display the issue in decreasing order of line numbers for each file. This is because fixing pep8 issues from top to bottom may result in the bottom issues' line numbers changing. Hence fixing pep8 issues from bottom to top is more convenient.

**Comment by OrkoHunter** [comment]
I appreciate the concern and there would be no harm in adding a new option through `.pep8speaks.yml` file.

**Comment by chinskiy** [comment]
@Punyaslok try to add to .pep8speaks.yml
`descending_issues_order: True`

**Comment by chinskiy** [comment]
@OrkoHunter I think this issue can be closed
