### ISSUE TITLE
Exclude option is ignored

### ISSUE THREAD

**Issue by daviddavis** [pep8speaks-org/pep8speaks#52]
It looks like the `exclude` option in `.pep8speaks.yml` is being ignored.

I have an example repository set up:

https://github.com/daviddavis/pep8speaks-exclude

You can see that I am excluding the docs directory:

https://github.com/daviddavis/pep8speaks-exclude/blob/master/.pep8speaks.yml#L7

However, on PRs, pep8speaks still shows errors for files in the excluded directory:

https://github.com/daviddavis/pep8speaks-exclude/pull/2

Running pycodestyle locally with `--exclude` works:

```
$ pycodestyle --max-line-length 100 .
./docs/conf.py:1:1: E265 block comment should start with '# '
./docs/conf.py:3:1: E265 block comment should start with '# '
$ pycodestyle --max-line-length 100 --exclude docs .
$
```

Not sure if I doing something wrong? I also tried a string instead of an array (ie `exclude: docs`) but that didn't work either.

**Comment by daviddavis** [comment]
It looks like the problem is that [pep8speaks is just running pycodestyle on a file `file_to_check.py`](https://github.com/OrkoHunter/pep8speaks/blob/1c4e91530e23ba86b4bf2c3f84981548e7684b2a/pep8speaks/helpers.py#L231) so excludes never matches anything. We need to filter the files before this point. Opening a PR https://github.com/OrkoHunter/pep8speaks/pull/53.

**Comment by OrkoHunter** [comment]
Hi @daviddavis !

It looks like `filename_match` needed more tweaks than the fnmatch. I have added them in [this commit](https://github.com/OrkoHunter/pep8speaks/commit/d72b3ce71a8f8f975e6cfd9edf0d4d3e768562e4). Can you please verify it?

**Comment by daviddavis** [comment]
@OrkoHunter looks good and works well! 👍 

Thank you!
