### ISSUE TITLE
Read the configuration file form PR branch

### ISSUE THREAD

**Issue by rlaverde** [pep8speaks-org/pep8speaks#55]
Reading the` .pep8speaks.yaml` file from PR branch instead of base branch, will make easy to test changes in the config file.

**Comment by OrkoHunter** [comment]
Hello @rlaverde 

Thanks for opening an issue about it. The default behavior for reading the config file *was* to read it from the PR branch (like Travis, and others) itself. It was working fine, when suggestions brought up some issues -
1. If there were multiple Pull Requests pending, all of them had to be rebased, just to ignore some errors.
2. Same goes for a change every time. Changing it on the main repo will instantly reflect on old/new PRs.

Hence, [a month ago](https://github.com/OrkoHunter/pep8speaks/commit/e4f04db6cd08d8f510c8055e3d487b341d23aa9e) the behavior was changed.

**Comment by rlaverde** [comment]
I understood, maybe the PR branch could be a fallback if the there isn't a config file in the main branch. Or maybe and option mentioning the bot, i. e. "@pep8speaks read config from PR branch".

**Comment by OrkoHunter** [comment]
Thank you @rlaverde for your suggestion! PEP8Speaks will now look at the branch of Pull Request as a fallback if no config is found on the base branch.
