### ISSUE TITLE
Change project name to 'parseltongue'

### ISSUE THREAD

**Issue by leblancfg** [pep8speaks-org/pep8speaks#68]
If you're going to converse with a Serpent, might as well use [the correct word](https://en.wikipedia.org/wiki/Magic_in_Harry_Potter#Parseltongue) for it, right?

This is meant to be tongue-in-cheek, of course.

**Comment by OrkoHunter** [comment]
Being a mudblood myself, I fear the dark lord just too much. Hence I dropped the idea.
