### ISSUE TITLE
The bot doesn't seem to work at all

### ISSUE THREAD

**Issue by AileenLumina** [pep8speaks-org/pep8speaks#74]
Check this out: https://github.com/Dwarf-Community/Dwarf/pull/4#pullrequestreview-80548938

Am I doing something wrong? I did add the bot to all repositories of the organization, so I really don't know what's the issue here...

**Comment by OrkoHunter** [comment]
Hi @AileenLumina 
Thanks for reporting this. Yes the bot has been installed in the organization. Let me get back to you once I debug this.

**Comment by OrkoHunter** [comment]
Hello @AileenLumina,
Thank you very much for reporting the issue. There was indeed a bug which led the app to crash when there were multiple files involved in the Pull Request. Fixed in #75. PEP8Speaks should be working now. 
Thanks and cheers !
