### ISSUE TITLE
PEP8Speaks itself has dozens of PEP 8 issues

### ISSUE THREAD

**Issue by CAM-Gerlach** [pep8speaks-org/pep8speaks#91]
I noticed while opening the code in Spyder to fix #90 with real time code style analysis (with ``pycodestyle``) turned on, that dozens and dozens of PEP 8 issues popped up in the main files,  While it may not be the end of the world, it seems rather significant that a project who's goal is to clean up PEP 8 issues has so many of its own, heh. If feasible, to put forth a good example, it might be a good idea to clean house sometime when no PRs, etc. are open to cause conflicts. I'm more than happy to do it if such is desired. The built in static analysis (``pylint``) also detected a bunch of issues, which can be conservatively fixed at the same time.

**Comment by feerrenrut** [comment]
I started looking at PRs here for an example of pep8speaks in use. It seems it might serve multiple purposes to "eat your own dogfood" in this case. Using pep8speaks on this project will provide a demonstrate the features, and also help to clean up the violations in the project.

I hope this is taken as constructive.

**Comment by CAM-Gerlach** [comment]
Also, at the same time, I can fix a couple related standards-compliance issues, namely:

* A few files are missing terminating EOLs, as is required by a number of standards (and triggering Git warnings, breaking a number of *nix utilities, etc), namely:

  ```
  pep8speaks/__init__.py
  requirements/test.txt
  templates/index.html
  tests/__init__.py
  ```

* A number of files are missing the ``# -*- coding: utf-8 -*-`` line required by PEP 263; however, if its not compatible with Python 2 or at least realistically expected to be run on such, then it isn't strictly necessary. The files:

  ```
  ./conftest.py
  ./pep8speaks/constants.py
  ./pep8speaks/models.py
  ./pep8speaks/utils.py
  ./pep8speaks/__init__.py
  ./tests/pep8speaks/test_handlers.py
  ./tests/pep8speaks/test_helpers.py
  ./tests/pep8speaks/test_models.py
  ./tests/pep8speaks/test_utils.py
  ./tests/test_app.py
  ./tests/__init__.py
  ```

**Comment by OrkoHunter** [comment]
Hi @CAM-Gerlach ! Thank you for your suggestions on the PEP 8 issues and note about EOLs. I agree that the code itself had those issues.

As of today, there are no style issues detected by `pycodestyle` in the project. As a note, I would like to add that there are some [configurations](https://github.com/OrkoHunter/pep8speaks/blob/master/.pep8speaks.yml) of pycodestyle that this project uses. I should probably add it to cfg files for other tools to read them. Related : #95
