### ISSUE TITLE
No easy way to test locally with pycodestyle command line if we have a custom config in .pep8speaks.yml

### ISSUE THREAD

**Issue by Silentphantom62** [pep8speaks-org/pep8speaks#94]
I have a custom config in .pep8speaks.yml
But if I want to run the pycodestyle locally with respect to my custom config I have to create a setup.cfg file in the repo change the pycodestyle parameters mentioned in yaml to different format and then test it.

Is there an easier/better way to do this?

**Comment by OrkoHunter** [comment]
I'm afraid not. This is basically what the tool is doing internally.
