### ISSUE TITLE
Use flake8 settings from setup.cfg

### ISSUE THREAD

**Issue by datapythonista** [pep8speaks-org/pep8speaks#95]
pep8speaks allows setting up flake8 parameters using the config option `pycodestyle`. For example:
https://github.com/pandas-dev/pandas/blob/master/.pep8speaks.yml#L8

But Python projects/flake8 already defines a way to specify those, which is in the `flake8` section of `setup.cfg`. For example:
https://github.com/pandas-dev/pandas/blob/master/setup.cfg#L14

I think it'd be nice to keep the `pycodestyle` setting, but in case it's not present, it should look for the options in `setup.cfg` and use them. This way, projects don't need to maintain two different copies of the flake8 settings, and there are no mismatches in the errors the pep8speaks reports, and what the CI of the projects are linting.

**Comment by OrkoHunter** [comment]
Hello @datapythonista !

Thank you so much for the wonderful suggestion. A [new release](https://github.com/OrkoHunter/pep8speaks/releases) of the app has been pushed, tested and deployed with your suggestion. You can now remove the `pycodestyle` section from `.pep8speaks.yml` and it will read configurations from the `[flake8]` section of `setup.cfg`.

**Comment by datapythonista** [comment]
thanks @OrkoHunter, I created this issue in pandas, will let you know how it works: https://github.com/pandas-dev/pandas/issues/25605

thank you!

**Comment by eggplants** [comment]
Now, pep8speaks seem to ignore flake8 configurations in `setup.cfg`.
