### ISSUE TITLE
Does pep8speaks follow #noqa flags?

### ISSUE THREAD

**Issue by fmaussion** [pep8speaks-org/pep8speaks#96]
We are in the process of moving from stickler-ci to pep8speaks, but we get false alarms from lines annotated with a `#noqa` (see [this PR](https://github.com/pydata/xarray/pull/2467#issuecomment-427535087)).

Is this expected? Is there a way to avoid these? Thanks a lot!

**Comment by OrkoHunter** [comment]
Hey @fmaussion! Thank you for reaching out to me about the issue.

I wasn't aware of `#noqa` until now. PEP8Speaks uses [pycodestyle](https://github.com/PyCQA/pycodestyle) as the linter. So, the error messages are not up to me.

I found [some](https://github.com/PyCQA/pycodestyle/issues/180) [discussion](https://github.com/PyCQA/pycodestyle/issues/480) about implementing it in pycodestyle, but if I am not wrong, it still remains a missing feature.

So, yes this is expected as of now, and the only way to avoid it is to put E741 in the ignores list of `.pep8speaks.yml`

**Comment by fmaussion** [comment]
Thanks for the info! Maybe we'll keep this issue open for future reference.

**Comment by OrkoHunter** [comment]
Hi @fmaussion !

I can see that `E741` has been added to the ignore list in [`.pep8speaks.yml`](https://github.com/pydata/xarray/blob/master/.pep8speaks.yml). Does @pep8speaks still complain about any `#noqa` errors other than E741?

I would also like to let you know that there is no need to maintain two copies of pycodestyle/flake8 settings in `.pep8speaks.yml` and `setup.cfg`. You can go ahead and remove `pycodestyle:` section from `.pep8speaks.yml` and it will read the `[flake8]` section of `setup.cfg` file. See https://github.com/OrkoHunter/pep8speaks/issues/95 and https://github.com/pandas-dev/pandas/issues/25605

**Comment by OrkoHunter** [comment]
Hi @fmaussion !

PEP 8 Speaks can now support `#noqa`. After #115, projects can choose between `pycodestyle` and `flake8` as their linter. The `scanner.linter` option `.pep8speaks.yml` should be set to `flake8`.

Example `.pep8speaks.yml` -
```yml
scanner:
    diff_only: True
    linter: flake8

flake8:  # Skip this if you have [flake8] in your setup.cfg file
    ignore:
        - EXXX
        - WXXX
```

[Complete configuration details is in the README](https://github.com/OrkoHunter/pep8speaks#configuration). I am going to close this issue. Let me know if you have any questions/comments!
