### ISSUE TITLE
.pep8speaks.yml not parsed?

### ISSUE THREAD

**Issue by tammojan** [pep8speaks-org/pep8speaks#97]
I'm using pep8speaks on a (public) repository with long lines. Pep8speaks [complains](https://github.com/apertif/apercal/pull/92#issuecomment-444785089) about the lines being longer than 79 characters, even though I set `max-line-length: 120` in [.pep8speaks.yml](https://github.com/apertif/apercal/blob/master/.pep8speaks.yml). I have the impression that the config is ignored, but I have no way to debug this. Could someone have a look?

**Comment by OrkoHunter** [comment]
Hi @tammojan! Thank you for raising the issue. The config file looks correct to me. I can see that the [branch](https://github.com/apertif/apercal/tree/first_aoflag) used to create the PR does not have .pep8speaks.yml file. Please let me know if the problem is solved by rebasing.

**Comment by tammojan** [comment]
Thanks for having a look! I rebased the branch, now it does have a [.pep8speaks.yml](https://github.com/apertif/apercal/blob/first_aoflag/.pep8speaks.yml). Still the same [complaints](https://github.com/apertif/apercal/pull/92#issuecomment-444785089), the line length 120 from the yml is not respected.

**Comment by tammojan** [comment]
Hi @OrkoHunter , could you have another look please? I think all PRs (e.g. https://github.com/apertif/apercal/pull/114) now have the proper .pep8speaks.yaml but still I get warnings that should have been silenced.

**Comment by OrkoHunter** [comment]
Hi @tammojan @imhassantariq, let me have a look on the configuration issue.

**Comment by OrkoHunter** [comment]
On a test PR, I can see that the bot is respecting the configuration file of the [test repo](https://github.com/OrkoHunter/test-pep8speaks/pull/74).

I will now consider the special case of your Pull Request.

**Comment by OrkoHunter** [comment]
I used the same configuration as https://github.com/apertif/apercal/blob/master/.pep8speaks.yml and it worked well on the test repository.
https://github.com/OrkoHunter/test-pep8speaks/pull/75

**Comment by OrkoHunter** [comment]
I created a new pull request with exceeding line length limit, and it seems to be working well with the configuration file. - https://github.com/apertif/apercal/pull/115

**Comment by OrkoHunter** [comment]
The comment in the [pull request](https://github.com/apertif/apercal/pull/114) you mentioned points to a repository https://github.com/tammojan/apercal/

Is it possible that you moved this project from one account to another? Maybe that is causing some issues. I believe if you create a fresh Pull Request, everything should be good, like the [PR I created](https://github.com/apertif/apercal/pull/115). :)

**Comment by OrkoHunter** [comment]
Please re-open the issue if you see this behavior on any new Pull Request you create.

**Comment by tammojan** [comment]
Thanks again for looking into this. I just created a new PR and the issue still shows. See https://github.com/apertif/apercal/pull/116 . I cannot reopen this issue, perhaps you can do that for me?

I'm quite sure I did not move the repository from tammojan/apercal.

> The comment in the pull request you mentioned points to a repository https://github.com/tammojan/apercal/

I don't see which comment you refer to.

**Comment by OrkoHunter** [comment]
Hey @tammojan! Maybe I understand the issue. It is a case when a user A creates a PR on user B's repository while creating a branch on B's repository itself (no forks).

Let me get back to you in some time.

**Comment by OrkoHunter** [comment]
By the comment, I was referring to the highlighted line number in the [bot's comment](https://github.com/apertif/apercal/pull/116#issuecomment-449372760). Sorry, that is not relevant here

**Comment by OrkoHunter** [comment]
Hi @tammojan! I deployed the latest version of the code and re-delivered the payload of https://github.com/apertif/apercal/pull/116

It seems to be using the configuration file now. Can you please test it one more time on a new PR?

Thank you.

**Comment by tammojan** [comment]
Thanks, this solves the issue (tested in https://github.com/apertif/apercal/pull/117).

**Comment by OrkoHunter** [comment]
Awesome!
