### ISSUE TITLE
pep8speaks is not picking configurations file

### ISSUE THREAD

**Issue by imhassantariq** [pep8speaks-org/pep8speaks#98]
pep8speaks is not picking the configuration file ".pep8speaks.yml" automatically i have added this file in my PR but still it's showing error's. Even i have put this file in my master branch as well and created new PR but still it's not working.

**Comment by OrkoHunter** [comment]
The Pull Request where you saw this behavior is - https://github.com/ucsd-ets/edx-platform/pull/42

The comment on this PR by pep8speaks points to a repository/branch which does not exist anymore https://github.com/imhassantariq/edx-platform/, hence it can not pickup any configuration file. Some things changed after the PR was created and thus GitHub API is sending mixed up values.

I believe if you create any new Pull Request, things will be fine. :)
